"""empty message

Revision ID: 284c6cbbba29
Revises: f2a5e1167cd1
Create Date: 2018-06-07 16:25:02.854748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284c6cbbba29'
down_revision = 'f2a5e1167cd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cinemas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Float(precision=1), nullable=True),
    sa.Column('hallnum', sa.Float(precision=10), nullable=True),
    sa.Column('servicecharge', sa.Float(precision=2), nullable=True),
    sa.Column('astrict', sa.Integer(), nullable=True),
    sa.Column('flag', sa.Boolean(), nullable=True),
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cinemas')
    # ### end Alembic commands ###
