"""empty message

Revision ID: 3f7b5a48c510
Revises: 9934a1385681
Create Date: 2018-06-06 11:48:05.103114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f7b5a48c510'
down_revision = '9934a1385681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_letter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parentId', sa.Integer(), nullable=True),
    sa.Column('regionName', sa.String(length=50), nullable=True),
    sa.Column('cityCode', sa.Integer(), nullable=True),
    sa.Column('pinYin', sa.String(length=100), nullable=True),
    sa.Column('letter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['letter_id'], ['t_letter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('city')
    op.drop_table('letter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('letter',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('city',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('parentId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('regionName', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('cityCode', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('pinYin', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('letter_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['letter_id'], ['letter.id'], name='city_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('t_city')
    op.drop_table('t_letter')
    # ### end Alembic commands ###
