"""empty message

Revision ID: c361dc1edecb
Revises: 9201f2b189fd
Create Date: 2018-06-07 15:32:38.263045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c361dc1edecb'
down_revision = '9201f2b189fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('phone_2', sa.String(100), nullable=True))
    op.add_column('t_user', sa.Column('photo_1', sa.String(100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user', 'photo_1')
    op.drop_column('t_user', 'phone_2')
    # ### end Alembic commands ###
